server:
  port: 8111 # 服务端口

spring:
  profiles:
    active: dev
  application:
    name: houseServer # 服务名
  datasource: # mysql数据库连接
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/houseServer?serverTimezone=GMT%2B8
    username: root
    password: root
  #spring:
  jackson: #返回json的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

wx:
  apiUrl: https://api.weixin.qq.com/
  appId: xx
  secret: ll


#mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #mybatis plus sql语句打印的配置
  mapper-locations: classpath:com/professor/houseserver/dao/*.xml

logging:
  level:
    com.professor.houseserver: debug

